### ISSUE TITLE
Support new Plex Movie agent

### ISSUE THREAD

**Issue by adamgot** [adamgot/python-plexlibrary#90] opened 2020-08-14 08:55 UTC

**Comment by docmeth02** [comment] 2020-08-19 17:20
Should be a pretty easy fix. The new agent is called tv.plex.agents.movie instead of com.plexapp.agents.imdb for the legacy scanner. But there should probably be some kind of detection what kind of agent is used for the library. 
I can give it a shot and submit a pull request if you want. Or maybe you prefer to implement it yourself.

For anyone looking to fix this NOW. Change in plexutils.py:

```
if library_type == 'movie':
            params['type'] = 'movie'
            params['agent'] = 'tv.plex.agents.movie'
            params['scanner'] = 'Plex Movie Scanner'
```

Be aware that this change will make legacy movie libraries stop working.

**Comment by adamgot** [comment] 2020-08-19 18:52
@docmeth02 Please feel free to submit a PR if you want. Detecting “default” library agent might be useful, not sure, keep in mind that agent can differ from item to item, so they’ll all have to be considered.

**Comment by Migz93** [comment] 2020-08-19 19:24
@docmeth02 I've tried your changes but it doesn't work.
From what i understand the only bit that changed was changing the agent to tv.plex.agents.movie?

I'm going to assume because currently the new plex agent doesn't expose any GUIDs for external services, i.e that a movie is xx on IMDB or yy on TMDB that when the script checks what movies are in the Plex library it can't see any GUIDs it understands so thinks there are no movies.
Plex have advised that they'll be making these GUIDs available again in the XML, once those are available this (and many other 3rd party scripts) should be able to work with the new scanner. Unsure if it'll need some changes to the script itself though.
https://forums.plex.tv/t/native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/130

**Comment by Mnk3y** [comment] 2020-08-20 15:18
External ids are now available in version 1.20.1.3213. And yes, I think changes are still needed because it still does not work with the new server version.

**Comment by armin0012002** [comment] 2020-08-30 09:23
/opt/python-plexlibrary$ pip install -r requirements.txt
Collecting plexapi (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/55/37/02901be36dddc72f13218e439de0a72af655b74d4dcc2fa730bc647896fe/PlexAPI-4.1.0.tar.gz
PlexAPI requires Python '>=3.5' but the running Python is 2.7.17

**Comment by armin0012002** [comment] 2020-08-31 07:47
any fix yet for new plex agent ?

**Comment by Mnk3y** [comment] 2020-08-31 09:03
No, we have to wait for an update of the Plex API, because it cannot parse the new entries yet.
https://github.com/pkkid/python-plexapi/issues/534

**Comment by morganzero** [comment] 2020-09-17 16:27
Does it work for anyone yet?

**Comment by PearsonFlyer** [comment] 2020-09-25 12:56
Plexapi has been updated. Any chance we can take advantage of this yet? I miss my trending movies library :(

**Comment by morganzero** [comment] 2020-09-25 13:23
I 2nd this @PearsonFlyer

**Comment by adamgot** [comment] 2020-09-27 11:44
This is not yet in plexapi, waiting for this: https://github.com/pkkid/python-plexapi/issues/557

**Comment by xfouloux** [comment] 2020-10-06 04:44
> Should be a pretty easy fix. The new agent is called tv.plex.agents.movie instead of com.plexapp.agents.imdb for the legacy scanner. But there should probably be some kind of detection what kind of agent is used for the library.
> I can give it a shot and submit a pull request if you want. Or maybe you prefer to implement it yourself.
> 
> For anyone looking to fix this NOW. Change in plexutils.py:
> 
> ```
> if library_type == 'movie':
>             params['type'] = 'movie'
>             params['agent'] = 'tv.plex.agents.movie'
>             params['scanner'] = 'Plex Movie Scanner'
> ```
> 
> Be aware that this change will make legacy movie libraries stop working.

The problem with this solution is that like you said old agent match will not work, and when you switch to new agent, well if you don't do a plex dance, your movies are not rematched with the new agent i guess ? Maybe i'm wrong, but all my movies from before i switched to new agent are still matched by plexlibrary, only new ones are not.

So the best way would be to catch with agent was used to match movie, then do stuff

Thanks

**Comment by xfouloux** [comment] 2020-10-06 05:24
Also tautulli states that : The external metadata provider IDs have been added back in PMS 1.20.1.

so maybe we just need to update bit of the code

**Comment by PearsonFlyer** [comment] 2020-10-06 20:39
I made the change suggested above, and it still does not work. Also, someone said that only newly-scanned movies would have the new scraper format, and that is incorrect. Once you change, your whole movie library changes to the new scraper format.

**Comment by morganzero** [comment] 2020-10-06 21:06
Just to give some nuance in the matter.

This is what I did;

1. I changed the agent to Plex Movies on my Movie library, but not my dynamic library. Executed script.

Result: script could not recognise newly added movies with metadata from new Plex Movie Agent.

2. I deleted all the symlink and metadata from my dynamic library to start from scratch. I changed both my Movies library and the dynamic library to the new Agent. Executed script.

Result: script could not recognise newly added movies with metadata from new Plex Movie Agent. Nothing was added to to dynamic library.

3. I switched both libraries back to Plex Movie (Legacy) agent. Executed script.

Result: the script works. Back to square one.

Dynamic library = libraries created by python-plexlibrary.

**Comment by xfouloux** [comment] 2020-10-07 00:34
Yeah after hours of updating all my movie library metadata, well it's still not working, we need to check on how tautulli gets the guid from tmdb and imdb with the new scrapper and adapt :/

**Comment by josh-gaby** [comment] 2020-10-09 07:20
I've submitted a pull request (#96) that works around this issue, at least until the plexapi has been updated to support the tmdb and imdb ids and then it could be removed.

**Comment by samwiseg0** [comment] 2020-10-12 16:27
After speaking with @blacktwin. Searching with the GUID might not be possible. So https://github.com/pkkid/python-plexapi/issues/557 is not going to be a solution. It seems like the best way would be to pull the entire library once and create a reversed dictionary lookup. This pull request would need to be merged to make the reversed dictionary lookup work. https://github.com/pkkid/python-plexapi/pull/562

**Comment by josh-gaby** [comment] 2020-10-13 00:38
@samwiseg0 even with that pull request merged it would still require an api call for every single individual movie in the users libraries.

What are peoples thoughts on directly accessing the plex database for this? 
It's a simple sqlite connection and a very simple query like `SELECT t.tag, mdi.guid FROM metadata_items mdi 
JOIN taggings tg ON tg.metadata_item_id = mdi.id
JOIN tags t ON t.id = tg.tag_id AND t.tag_type = 314
WHERE mdi.metadata_type = 1
GROUP BY mdi.id, t.tag` returns the following data set:

plex://movie/5d9f3c6fe4fc29001eb6f051	imdb://tt3321300
plex://movie/5d9f3c6fe4fc29001eb6f051	tmdb://292040
plex://movie/5d9f3c6fe4fc29001eb6f051	tvdb://4167
plex://movie/5d776bad7a53e9001e72cef7	imdb://tt3703908
plex://movie/5d776bad7a53e9001e72cef7	tmdb://344041
plex://movie/5d776bad7a53e9001e72cef7	tvdb://5926
plex://movie/5d776b3d96b655001fe09882	imdb://tt3733774
plex://movie/5d776b3d96b655001fe09882	tmdb://301608
plex://movie/5d776b3d96b655001fe09882	tvdb://7515
plex://movie/5d776b26f617c90020172ac6	imdb://tt3203606
plex://movie/5d776b26f617c90020172ac6	tmdb://294016
plex://movie/5d776b26f617c90020172ac6	tvdb://6213
plex://movie/5d776b11594b2b001e6ce299	imdb://tt3170902
plex://movie/5d776b11594b2b001e6ce299	tmdb://287628
plex://movie/5d776b11594b2b001e6ce299	tvdb://16888
plex://movie/5d776b50fb0d55001f563a30	imdb://tt3949660
plex://movie/5d776b50fb0d55001f563a30	tmdb://308531
plex://movie/5d776b50fb0d55001f563a30	tvdb://1308
plex://movie/5d776acdad5437001f78918f	imdb://tt3332064
plex://movie/5d776acdad5437001f78918f	tmdb://266647
plex://movie/5d776acdad5437001f78918f	tvdb://1439

I only have a little over 3000 movies in my database but the above query takes 359ms to return, I don't imagine there would be any way to make that many http requests in a similar timeframe.

**Comment by xfouloux** [comment] 2020-10-13 04:01
Well i find this horrible, with more than 9k movies, let me tell you it will be horrible
How about forking or modifying the project to use radarr as source (as an option ?)

**Comment by samwiseg0** [comment] 2020-10-13 13:49
> What are peoples thoughts on directly accessing the Plex database for this? 

I am very opposed to anything that looks at the database. SQLite only allows one connection to a database so connecting to it while Plex is online is out of the question. Some other projects have done it but its a terrible idea and frankly I would never use it if the project went that route.

**Comment by samwiseg0** [comment] 2020-10-13 13:52
> Well i find this horrible, with more than 9k movies, let me tell you it will be horrible
> How about forking or modifying the project to use radarr as source (as an option ? because not everyone use radarr)

Not everyone would have radarr. We should figure out another way to pull this data from the plex API.

**Comment by josh-gaby** [comment] 2020-10-13 14:10
> > What are peoples thoughts on directly accessing the Plex database for this? 
> 
> 
> 
> I am very opposed to anything that looks at the database. SQLite only allows one connection to a database so connecting to it while Plex is online is out of the question. Some other projects have done it but it's a terrible idea and frankly I would never use it if the project went that route. 

What if a temporary copy of the database was taken to do the lookups on?

I've got it working without copying it and haven't had issues with my testing so far, but maybe taking a temporary copy of the database at initialisation would prevent any issues with Plex accessing it. My library is 3000+ movies and 26000+ tv episodes and the database is only ~300mb, copying that to a temp file wouldn't be to bad.

In saying that, SQLite does allow for multiple connections [multiple connections](https://sqlite.org/faq.html#q5) and since we are only ever reading from the database it shouldn't be a problem?

**Comment by samwiseg0** [comment] 2020-10-13 14:35
>In saying that, SQLite does allow for multiple connections and since we are only ever reading from the database it shouldn't be a problem?

This is my issue. "But only one process can be making changes to the database at any moment in time, however." What if Plex is writing to the database at the time you are trying to read it. It would be in a locked state. Again multiple things talking to a database without knowing about each other is a bad idea. 

> I've got it working without copying it and haven't had issues with my testing so far, but maybe taking a temporary copy of the database at initialization would prevent any issues with Plex accessing it. 

I think taking a copy would be ideal. But we should be pulling it just like the admin would from Plex web. `https://plex.server.com:32400/diagnostics/databases?X-Plex-Token=-XXXXXXXXXXXXXX`. Not sure if this is built into plexapi.

**Comment by adamgot** [comment] 2020-10-13 14:59
I would also very much like to avoid directly accessing the database. If that’s the only way it would be possible I think plexapi should do that and not this project, mainly so that we don’t have to keep up with database changes... 

Hopefully Plex might make this searchable in a future update?

**Comment by josh-gaby** [comment] 2020-10-13 15:10
@adamgot Guid search has been removed from plexapi and blacktwin said that it is not likely to be resolved in that project https://github.com/pkkid/python-plexapi/issues/557#issuecomment-707778230

**Comment by samwiseg0** [comment] 2020-10-13 15:44
We should be able to something like this. Again we need https://github.com/pkkid/python-plexapi/pull/562 merged. 
```python
guid_lookup = {guid: movie for movie in library.section('Movies').all() for guid in movie.guids}

guid = 'imdb://tt8695030'
movie = guid_lookup.get(guid)
```

**Comment by adamgot** [comment] 2020-10-13 19:26
@samwiseg0 this seems like the best way forward... will have to experiment with the performance. What I’m thinking is to save a cache of the entire library with all guids as lookup keys, and keep that cache updated by checking for recently added movies since last time.

**Comment by josh-gaby** [comment] 2020-10-13 19:57
> We should be able to do something like this. Again, we need https://github.com/pkkid/python-plexapi/pull/562 merged. 
> 
> ```python
> 
> guid_lookup = {guid: movie for movie in library.section('Movies').all() for guid in movie.guids}
> 
> 
> 
> guid = 'imdb://tt8695030'
> 
> movie = guid_lookup.get(guid)
> 
> ```

Agreed, that would be ideal but unless Plex change where/when they return the extra guids,that just won't be possible.

The problem is that library.section('Movies').all() will return the results of the library/sections/{section_id}/all Plex URL which just doesn't have those extra guids available so no pull request will make that work unless Plex changes the API again

**Comment by morganzero** [comment] 2020-10-13 20:01
Could the "solution" above  affect someone that has 20000 movies and 200,000 episodes i a bad way?

**Comment by adamgot** [comment] 2020-10-13 20:09
TV isn’t affected at all, but whatever solution will be adapted I will make sure is working fine with very large libraries as well.

**Comment by morganzero** [comment] 2020-10-13 20:12
Thanks, that's good to know! Keep up the good work!

**Comment by samwiseg0** [comment] 2020-10-13 21:10
> TV isn’t affected at all, but whatever solution will be adapted I will make sure is working fine with very large libraries as well.

It will be in the future. Rumor has it that they are working on their own for TV shows. I don't see this as an issue since we only will be pulling the master list once. 

If we track changes from recently added then this is a non issue. The first run will take longer but frankly this is not a time sensitive application so I don't see why it would matter if it took 10 seconds or 10 minuets to complete.

**Comment by josh-gaby** [comment] 2020-10-13 21:17
Does the recently added endpoint return items that have been modified or only newly added stuff? the cache wont be able to track someone fixing mismatched movies or changing the agent for an entire library if its is only returning new stuff

**Comment by samwiseg0** [comment] 2020-10-13 21:22
It pulls what has been recently added. If someone fix matches something that is not in recently added then no, it wont be included. 

We could put a flag to track changes only or do the entire lib when pulling. Even with 20000 items pulling the whole thing should not be too bad. I think we would have to pull it in 9999 increments anyway. So that is 3 calls.

**Comment by JonnyWong16** [comment] 2020-10-13 21:23
> Agreed, that would be ideal but unless Plex change where/when they return the extra guids,that just won't be possible.
> 
> The problem is that library.section('Movies').all() will return the results of the library/sections/{section_id}/all Plex URL which just doesn't have those extra guids available so no pull request will make that work unless Plex changes the API again

No, you're wrong. You're confusing the Plex API `/library/sections/<sectionID>/all` with the `plexapi` method `library.LibrarySection.all()`.

```python
>>> from plexapi.server import PlexServer
>>> plex = PlexServer("http://localhost:32400", token="xxxxxxxxxx")
>>> library = plex.library.section("Movies (preview)")
>>> guid_lookup = {guid.id: movie for movie in library.all() for guid in movie.guids}
>>> guid_lookup['imdb://tt0470752']
<Movie:245:Ex-Machina>
```

![image](https://user-images.githubusercontent.com/9099342/95917681-7fac8900-0d5f-11eb-9c2d-cfee068cd871.png)

**Comment by josh-gaby** [comment] 2020-10-13 22:04
@JonnyWong16 
You're right I was completely mixing them up, what is the performance like for your "Movies (preview) " library and how many items are in it?
I've just done a test with a small library of only 269 movies and it took ~33 seconds to load, that's around 8 items loaded per second for me. 

Definitely think a cache is going to be important if this method is used.

**Comment by JonnyWong16** [comment] 2020-10-13 23:09
It's a test library on my development server so it only has less than 10 movies.

You're not doing a time critical task. So it doesn't matter if it takes longer the first time.

**Comment by josh-gaby** [comment] 2020-10-14 01:22
@morganzero how big is your database file with that many entries? 
I'm curious if that many entries would make it large enough to be problematic for the copying of the database method because I have that working and it's super quick

**Comment by morganzero** [comment] 2020-10-14 05:15
@josh-gaby my com.plexapp.plugins.library.db is 1.10GB

**Comment by xfouloux** [comment] 2020-10-14 09:26
Indeed it would seem that reversed dictionary cache and UpdateAt methods are the way to go, downloading the DB all the time and doing queries in it is fine but not that great.
Even if the 1st time take hours, then the other task would just take a few minutes at most to add new movies from the recently added items. Also it allows you to not have to maintain a SQL query somewhere, and wonder at each update of plex if the db has been changed and breaks the query.

**Comment by armin0012002** [comment] 2020-11-04 03:17
https://github.com/mza921/Plex-Auto-Collections
this got fix with new plex agent , are you planning to update ?

**Comment by Arg0t** [comment] 2020-11-04 13:41
Does Tautulli API contain enough information to be able to replace using the Plex API to determine if an item exists in the library?

**Comment by PearsonFlyer** [comment] 2020-11-13 13:11
Just following up on this. I appears that PlexApi is not going to handle this. Does this mean PlexLibrary is dead for anything movie-related?  I'm getting an error now on my trending movies run. Just wondering if I need to just delete my Trending Movies library from Plex and forget about it.

AttributeError: 'MovieSection' object has no attribute 'ALLOWED_FILTERS'

**Comment by morganzero** [comment] 2020-11-14 12:38
@PearsonFlyer It's working like a charm for me as I'm still using the Legacy Agent. Not switching to new one unless this gets fixed or someone creates another way to enjoy both plexlibraries and the new Plex Agent.

**Comment by PearsonFlyer** [comment] 2020-11-14 13:12
@morganzero Of course it's working for legacy. This entire issue is related to the new movie agent. It doesn't apply to people using legacy.

**Comment by xfouloux** [comment] 2020-11-14 15:37
well the version in PR done by @josh-gaby works fine for me using the DB
i've done the explanation steps for docker and such in the PR if you wanna try it.
seems like the way to go for now unfortunately, because using tautulli, radarr or else is not something viable (some people don't use those tools)

**Comment by danz1995** [comment] 2020-11-16 01:33
Hey @xfouloux and @josh-gaby, how can I find the new Plex Agent guid and relate it to a imdb id? I am looking for inside the XML file, {baseurl}:{port}/libraries/sections/{key}/all/?X-Plex-Token={token}. If this is through another way other than XML, can you please give me some guide?

**Comment by josh-gaby** [comment] 2020-11-16 01:42
@danz1995 which direction are you trying to go? are you wanting to use a Plex Agent guid to look up the IMDb id or are you trying to go the other direction?

**Comment by danz1995** [comment] 2020-11-16 01:51
@josh-gaby I am able to obtain plex agent guid through XML, so, ideally, use that to loop up for the IMDb id of my library.

**Comment by josh-gaby** [comment] 2020-11-16 02:10
@danz1995 the results from the "/library/sections/{key}/all" query will contain a key for each item like "/library/metadata/{db_id}", if you make a request to that URL you will be able to find the imdb/tmdb/tvdb ids in the data returned. 

You will need to make a request for each media item you are trying to find the IMDb id for.

This will only work if the library being checked has had its metadata refreshed using Plex Media Server version 1.20.1.3213 or newer.

**Comment by danz1995** [comment] 2020-11-16 16:17
@josh-gaby I'll try this as soon as I stop working. Thanks!

**Comment by danz1995** [comment] 2020-11-17 13:08
@josh-gaby just wanted to come back and thank you, your suggestion worked like a charm!

**Comment by VP-EN** [comment] 2021-02-14 15:47
New python-plexapi is out, it seems to support the new Plex Movie Agent:
https://github.com/pkkid/python-plexapi/releases

Does this change anything in regards to this issue?

**Comment by adamgot** [comment] 2021-02-20 15:40
Hi everyone, had too much coffee today so I finally managed to convince myself to do this. (Boy is that some stale spaghetti code, eh?).

There's a branch plex-movie-agent in this repo which uses the suggested solution of building an in memory map of all the ids. It seems to work fine, but writing tests still feels to much like my day job for the amount of coffee I've had. So please give it a try and get back to me about any issues.

https://github.com/adamgot/python-plexlibrary/pull/103

**Closed** 2021-09-18 08:49 UTC
Labels: enhancement
